spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: test
    url: jdbc:oracle:thin:@192.168.1.249:1521/orcl
    username: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
